name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: pnpm test
        uses: creepinson/pnpm-action@master
        with:
          arguments: '["install", "test"]'
