name: Tests

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"
            - name: pnpm test
              uses: creepinson/pnpm-action@v2.1.0-alpha
              with:
                  args: "test"
