name: Tests

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"
            - uses: pnpm/action-setup@v1.2.0
              with:
                version: 4.11.1
                run_install: |
                  - recursive: false
            - name: Run tests
              run: pnpm test
