name: Tests

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"
            - name: npm install
              uses: jaid/action-npm-install@v1.2.1
              with:
                  packageManager: "pnpm"
            - name: Run tests
              run: pnpm test
